name: dispatched-clang-format

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: DoozyX/clang-format-lint-action@d3c7f85989e3b6416265a0d12f8b4a8aa8b0c4ff
      with:
        source: '.'
        exclude: './docs'
        extensions: 'c,cc,cpp,cxx,h,hpp,hxx,inl,inc,ixx'
        clangFormatVersion: 17
        inplace: True
    - uses: EndBug/add-and-commit@v9
      with:
        author_name: clang-format
        message: 'chore: style formatting'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
