name: vcpkg-update dep

on:
  workflow_dispatch:

###############################################################################
# Add this section to your workflow file does not already have it to enable
# the job to write the dependency metadata.
###############################################################################
permissions:
  contents: write

###############################################################################
# Add these environment variables to your workflow to enable the vcpkg
# dependency graph integration.
###############################################################################
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VCPKG_FEATURE_FLAGS: dependencygraph

jobs:
  build:
    runs-on: windows-latest

    # These steps assume an appropriate version of vcpkg is listed as a
    # submodule in your git repo. If it is not, you must update this workflow
    # to obtain it.

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'  
 
      - name: cd Plugin
        run: cd Plugin

      - name: Bootstrap vcpkg
        run: ${{ github.workspace }}/extern/vcpkg/bootstrap-vcpkg.bat

      - name: Directly invoke `vcpkg install`
        run: ${{ github.workspace }}/Plugin/vcpkg install

      - name: Build with G++
        run: g++ -I${{ github.workspace }}//Plugin/src -o main.cpp